# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blue Clean Jekyll Theme
email: shicky@gmail.com
description: Personal Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blueclean.sickyoon.com" # the base hostname & protocol for your site
author:
  name: 'Sick Yoon'
  email: shicky@gmail.com
  github_username: shicky
  linkedin_username: sickyoon

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

# Gems
gems:
- jekyll-paginate
- jekyll-assets

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
